### ISSUE TITLE
Fix visual bugs in activities

### ISSUE THREAD

**Issue by marcelo140** [cesium/atomic#104]
- [x] When a button is clicked and the action generates a new browser tab, the button becomes permanently blank
- [x] In the activities index, the `Next activities` and `Previous activities` should not be part of the `navbar`.
- [x] The `will_paginate` colorscheme must be improved. It's positioning feels displaced and can be tweaked.
- [x] Change the date format to a more succint and readable format. It must be translated to portuguese as well.
- [x] The activities index lack a margin. It has probably more bugs that we didn't perceive yet.
- [x] The message shown when there are no activities should be more friendly.

If someone notices more bugs be free to comment here.

**Comment by marcelo140** [comment]
What is the desired format for dates? @martinhoaragao @9thScientist 

**Current format:**  `%a %d, %b %Y` -> `Sex 09, Dez 2017`

**Option 1:**   `%d %B` -> `09 Dezembro` (no week day + no year)

**Option 2:**  `%A, %d %b` -> `Quarta, 09 Dezembro` (week day + no year)

If we want to show the year (always or maybe only to activities that don't happen in the current year)

**Option 3:**  `%d %b %Y` -> `09 Dez 2016` (no week day + year)

**Option 4:**  `%A, %d %b %Y` -> `Quarta, 09 Dezembro 2017` (week day + year)

Other suggestions?

**Comment by martinhoaragao** [comment]
Option 2? 
But I'm comfortable with all of them, to be honest.

**Comment by marcelo140** [comment]
@martinhoaragao Fixed the date's format. Feel free to improve the css and change the tables if you want ⛑

**Comment by marcelo140** [comment]
Fixed in https://github.com/cesium/atomic/pull/127
