### ISSUE TITLE
Add partners resource

### ISSUE THREAD

**Issue by marcelo140** [cesium/atomic#118]
# Description

Currently, the partners are updated using an yaml file and require developer intervention. It would be nice to add a partners resource for DREP to update it by themselves.

# Required changes

- Add a model to represent a partner.
- Add routes to handle the requests
- Add a controller to handle the new routes: `index`, `new`, `edit`, `destroy`. Note that edit and destroy methods should also delete the image associated with the partner.
- Remove the `partners` route from the `welcome_controller`
- Add views for index, new and edit. The partners view from the welcome controller can be reused as the index view.
- Restrict users who can use the `new`, `edit` and `destroy` methods using cancancan.

## About the modeling

To model the partner an extra model to represent the advantages may be required. Other option would be to simply have a text description in the partners use markdown to render it, which would also allows us to present the advantages as a list. Personally I'm more fond of the markdown option since it would be easier to implement and we would end with a more flexible solution. @fribmendes input on this.

**Comment by 0urobor0s** [comment]
Closed by [2e0e8f37c2049004152463bd28b8df2fcc7e4dba](https://github.com/cesium/atomic/commit/2e0e8f37c2049004152463bd28b8df2fcc7e4dba)
