### ISSUE TITLE
Authentication with identity

### ISSUE THREAD

**Issue by ZePedroResende** [cesium/atomic#153]
Right now we have different profiles for the same user when using different omniauth providers.
A user should have different identities for different providers.

**Comment by ZePedroResende** [comment]
@marcelo140 a user right now has an account for each method of authentication, the way to mitigate this ,per the documentation of ominiauth , is to create an identity for each provider in the same user , so we can login to the same user with diferent providers.

**Comment by marcelo140** [comment]
I don't understand how would we do this though. How would we link both providers to the same identity?

As i said in https://github.com/cesium/atomic/issues/132, I was thinking in redirecting users to a registration page after authenticating for the first time, similar to the way we do in intra. Users would be able to realize they're creating a new account and we would have more complete profiles.

Tell me more about your idea and share the link to that documentation page if you don't mind :grinning:

**Comment by ZePedroResende** [comment]
@marcelo140  i and @0urobor0s  saw this identity stuff here https://github.com/omniauth/omniauth/wiki/Managing-Multiple-Providers

**Comment by marcelo140** [comment]
Oh, I understand what you mean now. I'm all for it. I have a local branch where I already moved user attributes from the `user` (identities) to `member` (our actual users) which contributes to this issue. 

I'll try to merge it soon and probably close https://github.com/cesium/atomic/issues/132 so we can divide it into multiple smaller issues. I was thinking in something like

- redirect users to a registration page when authenticating for the first time
- improve user profile pages to reflect the data we have on them
- allow them to edit their profile
- allow them to link other oauth providers to their account

Am I missing something?

**Comment by 9thScientist** [comment]
User:
 - student number *
 - course *
 - email
 - telephone number
 - name *
 - hahsname **
 - status {undef, member, buddy} ***
 - avatar
 - admin

\*   - Cannot be changed if status is `member`
**  - Cannot be changed
*** - Can only be changed by an admin

**Comment by MarioRodrigues10** [comment]
Due to a change of the codebase and the stack used, we decided to close this issue. :pray:
