### ISSUE TITLE
Admin permissions

### ISSUE THREAD

**Issue by marcelo140** [cesium/atomic#154]
We need to decide how will we handle permissions. There are currently two PRs that are approaching the issue differently.

- https://github.com/cesium/atomic/pull/128 is grouping all permissions in activity's admin, leading only to full admins.

- https://github.com/cesium/atomic/pull/149 is separating in multiple administration roles.

We should discuss which approach we will converge to. Is it necessary to handle permissions differently for cesium's direction? @machadovilaca @ZePedroResende @0urobor0s @martinhoaragao

**Comment by 0urobor0s** [comment]
For the time being I think we should use "full admins" and in a different PR separete this, or not.
We shouldn't do this in a PR that as little to do with this.

**Comment by marcelo140** [comment]
After some discussion, it was decided we will have a single admin who can manage news, partners, activities, etc. It was referred that, once the platform was used to manage users, it could be useful to have a separate admin permission to manage users.

**Comment by MarioRodrigues10** [comment]
Due to a change of the codebase and the stack used, we decided to close this issue, although this problem will be solved in this new version of Atomic. :pray:
