### ISSUE TITLE
Add a way to export list of enrolled

### ISSUE THREAD

**Issue by nelsonmestevao** [cesium/atomic#171]
In some events, we need to send emails for a bunch of different reasons. If it is only one person that we are trying to get in touch with it's easy. However, more often than not it will be everyone.

It would be nice to be able to download a csv of the enrolled with the email contact (I know some of them will not have the email available).

**Comment by MarioRodrigues10** [comment]
Due to a change of the codebase and the stack used, we decided to close this issue, although this problem will be solved in this new version of Atomic. :pray:
