### ISSUE TITLE
Maintain older teams

### ISSUE THREAD

**Issue by 0urobor0s** [cesium/atomic#177]
Per the title it would be nice if we could keep the older teams and it's members around beside the git history.

**Comment by nelsonmestevao** [comment]
@0urobor0s do you have any example of how we could do this? Would a link in the bottom to the previous team be any good?

**Comment by 0urobor0s** [comment]
@nelsonmestevao I was thinking of simply adding some kind of pagination, so you could do that. You could even use the same format as is now.

**Comment by miguelbrandao** [comment]
@machadovilaca insists on this. He is extremely worried he'll be forgotten

**Comment by MarioRodrigues10** [comment]
Due to a change of the codebase and the stack used, we decided to close this issue, although this problem is solved in this new version of Atomic. :pray:
