### ISSUE TITLE
Improve 404 page design

### ISSUE THREAD

**Issue by ruilopesm** [cesium/atomic#347]
To something like this:
![image](https://github.com/cesium/atomic/assets/76881129/c784f616-0b2d-4c65-a806-0e02f39acdf3)
A "Go back" button is in fault, by the way.

**Comment by anubhav1206** [comment]
Where exactly is the file located?

**Comment by ruilopesm** [comment]
Hello, @anubhav1206 👋🏼
Thanks for wanting to contribute to our project 😄
The file location is: https://github.com/cesium/atomic/blob/develop/lib/atomic_web/templates/error/404.html.heex.
Tell me if you have any problem while developing the page or testing it 🙏🏼

**Comment by anubhav1206** [comment]
> Hello, @anubhav1206 👋🏼 Thanks for wanting to contribute to our project 😄 The file location is: https://github.com/cesium/atomic/blob/develop/lib/atomic_web/templates/error/404.html.heex. Tell me if you have any problem while developing the page or testing it 🙏🏼

Thank You
