### ISSUE TITLE
Purge the color orange

### ISSUE THREAD

**Issue by feliciofilipe** [cesium/atomic#389]

**Comment by MarioRodrigues10** [comment]
Which color do you think would be a good substitute?

**Comment by feliciofilipe** [comment]
Indigo to start. But the whole design needs to be rethinking imo.

A light theme with all the colors in pastel for details like notion seems what fits the best.

**Comment by ruilopesm** [comment]
We decided to stick with orange.

**Comment by feliciofilipe** [comment]
Have you considered white on white like linear?

![image](https://github.com/cesium/atomic/assets/55213469/bbbc3757-8014-44ed-8966-c67b3735c6fb)
