### ISSUE TITLE
Fix 'Become a Member' button

### ISSUE THREAD

**Issue by joaofcosta** [cesium/atomic#80]

**Comment by martinhoaragao** [comment]
What happened here? Clicking the button had mailto before, right?

**Comment by joaofcosta** [comment]
@martinhoaragao Don't know but you can check that in production the old behaviour, with `href='#'`, is present. This is weird... Can you fix this? 🤔

**Comment by martinhoaragao** [comment]
Should be taken care of now @joaofcosta

**Comment by joaofcosta** [comment]
Yes, this is fixed @martinhoaragao :+1:

**Comment by fribmendes** [comment]
thx for the timely response, mate. cheers 👍
