### ISSUE TITLE
Missing transactions

### ISSUE THREAD

**Issue by fntneves** [cesium/atomic#84]
I was diving into the code and realized that you are not using transactions anywhere.

Since there are situations where you are running several queries against the database, adding transactions becomes a **must**, despite of expecting that only one or two people will handle the application. Otherwise, users will get unexpected and occasional errors.

An example:

https://github.com/cesium/atomic/blob/361087a18b41f4104015e7a0fc5d496a4d93465a/app/controllers/terms_controller.rb#L19-L28

**Comment by fribmendes** [comment]
Also, stick this into services and spare yourself some trouble.

**Comment by marcelo140** [comment]
The only code that currently needs transactions is `departments_controller`, which is dead code. Should we just remove the trash or do you wish to keep it for future development?

Personally, I prefer a clean working repo. @0urobor0s @ZePedroResende

**Comment by 0urobor0s** [comment]
Same, also #159 revises this.
