### ISSUE TITLE
Refactor test suite

### ISSUE THREAD

**Issue by marcelo140** [cesium/atomic#92]
Most of the application tests are missing or failing and the factories are either outdated or generating objects with hard coded fields. Therefore, I suggest a refactor of both the factories and the the entire test suite.

**Comment by fribmendes** [comment]
I have a suggestion. How about I do a testing workshop?

**Comment by martinhoaragao** [comment]
@fribmendes for rails or general?

**Comment by fribmendes** [comment]
@martinhoaragao I was thinking of just overall Rails testing patterns but of course that comes with general testing patterns, maybe throw in a bit of TDD. Also, what I think when writing tests, what I think when I am reading your tests, how to refactor and when to test and not to test. All while refactoring the test suite and adding more tests to atomic.

I don't know what you are thinking about exactly but my suggestion would be a small internal workshop for the devs working on this.

I wouldn't go about explaining what testing is, I'm assuming people already know. I'm also not stopping to help install Ruby and Rails or teach the language or whatever. I assume people already know that as well and have this project set up. With those requirements in mind, it makes sense to be an internal workshop, but if you think it's not cool to have it be closed and want to include other people I'd rather have it be very limited in the number of participants.

**Comment by martinhoaragao** [comment]
@fribmendes Sounds fine by me. 

If they absorb the information to pass on to other developers who may join this or another project, later on, all the better.

**Comment by marcelo140** [comment]
Is there any idea when will this talk happen? I mean, at least the month or something?

**Comment by fribmendes** [comment]
It happened. See #145

**Comment by fribmendes** [comment]
Closed by #145
